In [1]:
import numpy as np 
import pandas as pd

In [2]:
Data = {"Names":["Ramesh","Suresh","Satish",np.nan],
       "Age":[np.nan,22,25,27],
       "City":["Pune","Pune",np.nan,"Hyd"]}

df=pd.DataFrame(Data)
df.to_csv("data_missing_1.csv",index=False)
df

    Names   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0  Pune
2  Satish  25.0   NaN
3     NaN  27.0   Hyd

In [3]:
Data = {"Names":["Ramesh","Suresh","Satish",None],
       "Age":[None,22,25,27],
       "City":["Pune","Pune",None,"Hyd"]}

df1=pd.DataFrame(Data)
df1.to_csv("data_missing_2.csv",index=False)
df1

    Names   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0  Pune
2  Satish  25.0  None
3    None  27.0   Hyd

In [4]:
df.dtypes

Names     object
Age      float64
City      object
dtype: object

In [9]:
df.isnull()    #int Nan  &  str None

   Names    Age   City
0  False   True  False
1  False  False  False
2  False  False   True
3   True  False  False

In [6]:
df.isnull().sum()       # show the missng value

Names    1
Age      1
City     1
dtype: int64

## Fillna

In [7]:
df.fillna(30)   # only integer but apply the all

    Names   Age  City
0  Ramesh  30.0  Pune
1  Suresh  22.0  Pune
2  Satish  25.0    30
3      30  27.0   Hyd

In [8]:
df["Age"].fillna(30)

0    30.0
1    22.0
2    25.0
3    27.0
Name: Age, dtype: float64

In [13]:
df[["Age"]].fillna(30)

    Age
0  30.0
1  22.0
2  25.0
3  27.0

- the above one is we are fill in randamly 

- all the columns are filled with random number 

- it is not a good apporch becouse in the data we hve dieffrent data types

**What is the diffrence between np.nan & None**

In [14]:
np.nan+5

nan

In [10]:
None+5

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [11]:
arr1=np.array([1,2,np.nan,3])   # it is int   / floats value
arr2=np.array([1,2,None,3])     # it is str

In [13]:
arr1

array([ 1.,  2., nan,  3.])

In [18]:
arr2

array([1, 2, None, 3], dtype=object)

In [19]:
np.nansum(arr1),np.sum(arr1)

(np.float64(6.0), np.float64(nan))

In [20]:
# np.sum(arr2)
#TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

- np.nan represent **float type**

- None represent **object value**

- if data opreation related to Math then nan formate is better

**fill the value baased on specific columns**

In [21]:
# df.fillna()
df["Names"].fillna("Manish")

0    Ramesh
1    Suresh
2    Satish
3    Manish
Name: Names, dtype: object

**Fill with the methods**

- Whenerver we are using methods no need to porovide values

- pad 

- bfill

- ffill

- backfill

In [15]:
df

    Names   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0  Pune
2  Satish  25.0   NaN
3     NaN  27.0   Hyd

In [17]:
import warnings 
warnings.filterwarnings('ignore')
df.fillna(method='pad')

    Names   Age  City
0  Ramesh   NaN  Pune
1  Suresh  22.0  Pune
2  Satish  25.0  Pune
3  Satish  27.0   Hyd

In [24]:
import warnings
warnings.filterwarnings('ignore')
df.fillna(method='pad',axis=1)  # zero columns wise / one is row wise

    Names     Age  City
0  Ramesh  Ramesh  Pune
1  Suresh    22.0  Pune
2  Satish    25.0  25.0
3     NaN    27.0   Hyd

**Mean-Median-Mode**

In [25]:
age_mean=df["Age"].mean()
df.fillna(age_mean)

       Names        Age       City
0     Ramesh  24.666667       Pune
1     Suresh  22.000000       Pune
2     Satish  25.000000  24.666667
3  24.666667  27.000000        Hyd

In [26]:
age_mean=df["Age"].median()
df["Age"].fillna(age_mean)

0    25.0
1    22.0
2    25.0
3    27.0
Name: Age, dtype: float64

In [27]:
age_mean=df["Age"].mode()
df["Age"].fillna(age_mean)

0    22.0
1    22.0
2    25.0
3    27.0
Name: Age, dtype: float64

In [28]:
mode=df["City"].mode()
mode.values

array(['Pune'], dtype=object)

In [29]:
age_median=df["Age"].median()
age_median.values

AttributeError: 'float' object has no attribute 'values'

**KNN Immputer**

- K - Nerarest Nieghbours

- where k = hyper parameter which means thr user change 

- idea : instend of tacking all the sample average

    - dirst fix the neighbours number i.e.k

    - Then fine the neighbours using distance metric 

    - then take the avrage of those to fill the dample the missing value

In [1]:
import sklearn
from sklearn.preprocessing import StandardScaler 
from sklearn.preprocessing import MinMaxScaler 
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import KNNImputer

In [6]:
#import method 
#save method 
#fit transform

In [5]:
import pandas as pd
import numpy as np
from sklearn.impute import KNNImputer
x=[[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]] 
pd.DataFrame(x)

     0     1    2
0  1.0   2.0  NaN
1  3.0   NaN  3.0
2  NaN  60.0  5.0
3  8.0   8.0  7.0

In [10]:
import pandas as pd
import numpy as np
from sklearn.impute import KNNImputer
x=[[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]] 
impute = KNNImputer(n_neighbors=2,
                   weights='uniform')   # all obesrvation is equle 
impute.fit_transform(x)

array([[ 1. ,  2. ,  5. ],
       [ 3. , 31. ,  3. ],
       [ 5.5, 60. ,  5. ],
       [ 8. ,  8. ,  7. ]])

In [13]:
 import pandas as pd
import numpy as np
from sklearn.impute import KNNImputer
x=[[1,2,np.nan],[3,np.nan,3],[np.nan,60,5],[8,8,7]] 
impute = KNNImputer(n_neighbors=2,
                   weights='distance')
impute.fit_transform(x)

array([[ 1.        ,  2.        ,  3.93905505],
       [ 3.        , 31.        ,  3.        ],
       [ 3.25775362, 60.        ,  5.        ],
       [ 8.        ,  8.        ,  7.        ]])

**Transformations**

    - assume : data are follows normal distibution 

    - 1) Positive   - 2) Negative  - 3) No skew (ND)

In [18]:
import pandas as pd

In [19]:
path=r"C:\Users\Dell\Documents\NareshIT\EDA\datafiles\telecom_churn_data.csv"

In [20]:
churn=pd.read_csv(path)
churn

,year,customer_id,phone_no,gender,age,no_of_days_subscribed,multi_screen,mail_subscribed,weekly_mins_watched,minimum_daily_mins,maximum_daily_mins,weekly_max_night_mins,videos_watched,maximum_days_inactive,customer_support_calls,churn
0,2015,100198,409-8743,Female,36,62,no,no,148.35,12.2,16.81,82,1,4.0,1,0.0
1,2015,100643,340-5930,Female,39,149,no,no,294.45,7.7,33.37,87,3,3.0,2,0.0
2,2015,100756,372-3750,Female,65,126,no,no,87.30,11.9,9.89,91,1,4.0,5,1.0
3,2015,101595,331-4902,Female,24,131,no,yes,321.30,9.5,36.41,102,4,3.0,3,0.0
4,2015,101653,351-8398,Female,40,191,no,no,243.00,10.9,27.54,83,7,3.0,1,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,2015,997132,385-7387,Female,54,75,no,yes,182.25,11.3,20.66,97,5,4.0,2,NaN
1996,2015,998086,383-9255,Male,45,127,no,no,273.45,9.3,30.99,116,3,3.0,1,0.0
1997,2015,998474,353-2080,NaN,53,94,no,no,128.85,15.6,14.60,110,16,5.0,0,0.0
1998,2015,998934,359-7788,Male,40,94,no,no,178.05,10.4,20.18,100,6,NaN,3,0.0
1999,2015,999961,414-1496,Male,37,73,no,no,326.70,10.3,37.03,89,6,3.0,1,1.0

In [21]:
# churn rate 
#     A customer is leaving teh company 
#     an emplyee leaving the company
#     attribute rate

In [22]:
churn.columns

Index(['year', 'customer_id', 'phone_no', 'gender', 'age',
       'no_of_days_subscribed', 'multi_screen', 'mail_subscribed',
       'weekly_mins_watched', 'minimum_daily_mins', 'maximum_daily_mins',
       'weekly_max_night_mins', 'videos_watched', 'maximum_days_inactive',
       'customer_support_calls', 'churn'],
      dtype='object')

In [ ]:
- year : at what year enrolled int 

- customer_id : unique id of a custumer int 

- phone_no : Uniue phone no of a custumer int 

- gender : Gender either Male Female str

- age : number int

- no_of_days_subscribed : int 

- multi_screen : yes or no Object 1 2 3 4 : int 

- mail_subscribed : str object

- weekly_mins_watched : int 

- weekly_max_night_mins : int

- minimum_daily_mins : int 

- maximum_daily_mins : int 

- weekly_max_night_mins : int 

- videos_watched :  int 

- maximum_days_inactive : int

- customer_support_calls : str or int

- churn : stay or notstay : str

In [24]:
churn.dtypes

year                        int64
customer_id                 int64
phone_no                   object
gender                     object
age                         int64
no_of_days_subscribed       int64
multi_screen               object
mail_subscribed            object
weekly_mins_watched       float64
minimum_daily_mins        float64
maximum_daily_mins        float64
weekly_max_night_mins       int64
videos_watched              int64
maximum_days_inactive     float64
customer_support_calls      int64
churn                     float64
dtype: object

In [25]:
churn.head()

,year,customer_id,phone_no,gender,age,no_of_days_subscribed,multi_screen,mail_subscribed,weekly_mins_watched,minimum_daily_mins,maximum_daily_mins,weekly_max_night_mins,videos_watched,maximum_days_inactive,customer_support_calls,churn
0,2015,100198,409-8743,Female,36,62,no,no,148.35,12.2,16.81,82,1,4.0,1,0.0
1,2015,100643,340-5930,Female,39,149,no,no,294.45,7.7,33.37,87,3,3.0,2,0.0
2,2015,100756,372-3750,Female,65,126,no,no,87.30,11.9,9.89,91,1,4.0,5,1.0
3,2015,101595,331-4902,Female,24,131,no,yes,321.30,9.5,36.41,102,4,3.0,3,0.0
4,2015,101653,351-8398,Female,40,191,no,no,243.00,10.9,27.54,83,7,3.0,1,0.0

In [ ]:
churn == stay or not stay
          0.0    1.0
          No    Yes

In [27]:
churn['churn'].mean()

np.float64(0.13333333333333333)

In [28]:
male = 1 
female = 0

In [29]:
churn['maximum_days_inactive'].unique()

array([ 4.,  3., nan,  2.,  5.,  1.,  0.,  6.])

In [30]:
churn['maximum_days_inactive'].mean()

np.float64(3.2505070993914806)