- Generally Ml Models Developed by maths 

- Convert catagorical columns into Numerical column 

- Here we are transfrom the data

- Male== 0 and Female == 1 like that 

- this Method we called as **Encoding** 

- Feature Analysis : First 5 session 

- Feature Engineering  : Transform the data 

- Feature Selection : In machine Learning


- Before Model Development 

- We will do EDA : Exploratory Data nalysis 

    - feature(columns) analysis

        - Catagorical, Numerical, Outlier Analysis, Bivariate, Multivarate

        - we will get insight

    - Feature Engineering 

        - we will modify the data 

        - Models developed by maths

        - Encoding : Convert Catagorical data into Numerical Variables 

        - Scalling : All the Numerical Column makes under one scale 

        - Transformation : All the maths developed by assumption data follows Normal Distribution 

            - Convert skewed distribution to Normal 

    - Feature Selection

# there are three methods 

- map 

- LabelEncoder

- OneHotEncoder

# Method -1 : Map

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 


visa_df = pd.read_csv(r"Visadataset.csv")
cat = visa_df.select_dtypes(include='object').columns
num = visa_df.select_dtypes(exclude='object').columns

In [2]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [3]:
visa_df = pd.read_csv(r"Visadataset.csv")
sorted(visa_df['continent'].unique())

['Africa', 'Asia', 'Europe', 'North America', 'Oceania', 'South America']

In [4]:
visa_df['yr_of_estab'].nunique()

199

In [5]:
# create a dictionry assign a number start with zero 
# for each labels based on alphabetical order 
d = {'Certified':0, 'Denied':1}
#      key    value ,key value
d
print(d['Certified'])

0

In [6]:
# map the dictionary with column 
visa_df['case_status'].map(d)

# we will save the data into old column we will overwrite data 

visa_df['case_status'] = visa_df['case_status'].map(d)

In [7]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [8]:
# we will draw all together for case status column
visa_df = pd.read_csv(r"Visadataset.csv") 
# we because in above line we already assign a data into encoding then we ruun again then it will show error 
visa_df['case_status'].unique()
d = {'Certified':0, 'Denied':1}
visa_df['case_status'] = visa_df['case_status'].map(d)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [9]:
visa_df['continent'].unique()
d1 = {'Asia':0, 'Africa':1, 'North America':2, 'Europe':3, 'South America':4, 'Oceania':5}
visa_df['continent'] = visa_df['continent'].map(d1)

In [10]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,0,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,0,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,0,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,0,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,1,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,0,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,0,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,0,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,0,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,0,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

**create dictionary using for loop**

In [11]:
visa_df = pd.read_csv(r"Visadataset.csv") 
labels = visa_df['continent'].unique()    # write the all unique value like :- asia , africa
d = {}
for i in range(len(labels)):   #len of labels = 6
    keys = labels[i]
    d[keys]=i

d

{'Asia': 0,
 'Africa': 1,
 'North America': 2,
 'Europe': 3,
 'South America': 4,
 'Oceania': 5}

In [12]:
# we use sorted to alphabetical order 

labels = sorted(visa_df['continent'].unique())
d = {}
for i in range(len(labels)):
    keys = labels[i]
    d[keys]=i

d

{'Africa': 0,
 'Asia': 1,
 'Europe': 2,
 'North America': 3,
 'Oceania': 4,
 'South America': 5}

**using dictionary comprehension**

In [13]:
# using dictionary comprehension
labels = sorted(visa_df['continent'].unique())

d = {labels[i]:i for i in range(len(labels))}
d

{'Africa': 0,
 'Asia': 1,
 'Europe': 2,
 'North America': 3,
 'Oceania': 4,
 'South America': 5}

In [14]:
# using dictionary comprehension
labels = sorted(visa_df['education_of_employee'].unique())

d = {labels[i]:i for i in range(len(labels))}
d

{"Bachelor's": 0, 'Doctorate': 1, 'High School': 2, "Master's": 3}

In [15]:
visa_df = pd.read_csv(r"Visadataset.csv") 
labels = sorted(visa_df['continent'].unique())
d = {labels[i]:i for i in range(len(labels))}
visa_df['continent'] = visa_df['continent'].map(d)

In [16]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,1,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,1,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,1,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,0,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,1,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,1,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,1,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,1,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [17]:
visa_df = pd.read_csv(r"Visadataset.csv") 
for i in cat:
    labels = sorted(visa_df[i].unique())
    d = {labels[i]:i for i in range(len(labels))}
    visa_df[i] = visa_df[i].map(d)

In [18]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,0,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,1,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,2,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,3,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,4,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,17204,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,17205,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,17206,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,17207,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,17209,1,0,1,0,3195,1960,1,70876.9100,3,1,0

**step-1:categarical data to numerical data using the map**

In [19]:
# we will avoid case id 
visa_df = pd.read_csv(r"Visadataset.csv") 
for i in cat[1:]:
    labels = sorted(visa_df[i].unique())
    d = {labels[i]:i for i in range(len(labels))}
    visa_df[i] = visa_df[i].map(d)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,EZYV02,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,EZYV03,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,EZYV04,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,EZYV05,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,EZYV25477,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,EZYV25478,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,EZYV25479,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,EZYV25480,1,0,1,0,3195,1960,1,70876.9100,3,1,0

In [20]:
visa_df = pd.read_csv(r"Visadataset.csv")

# Method-2 LabelEncoder

package name: **sklearn**

    - class: **preprocessing**

        - method : **LabelEncod

- after comes like these then import the packages like these 

    - from sklearn.preprocessing import LabelEncoder
 

- all values after changing in these module on alphabetical order

In [21]:
from sklearn.preprocessing import LabelEncoder

- step-1: import the method

- step-2: save the method

- step-3: apply fit transform


- **fit_transfrom**

- fit : finding something

  - first we are finding dictionary
    
 
- transfrom : change the data

    - using the dictionay we are changing English to Number

In [22]:
from sklearn.preprocessing import LabelEncoder   # step-1
le = LabelEncoder()                              # step-2
le.fit_transform(visa_df['case_status'])         # step-3

array([1, 0, 1, ..., 0, 0, 0])

**step-2: Categoriacal data  to numerical data**

In [23]:
from sklearn.preprocessing import LabelEncoder  # step-1
le = LabelEncoder()       
for i in cat:          
  visa_df[i] = le.fit_transform(visa_df[i])

In [24]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,0,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,1,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,2,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,3,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,4,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,17204,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,17205,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,17206,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,17207,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,17209,1,0,1,0,3195,1960,1,70876.9100,3,1,0

# Method - 3: OneHotencoder

- The method name is: pd.get_dummies


|case_status|case_status_Denied|case_status_certified|
|-|-|-|
|Denied|1|0|
|Certifeid|0|1|

In [25]:
# read the data agein
visa_df = pd.read_csv(r"Visadataset.csv") 

pd.get_dummies(visa_df['continent'])

       Africa   Asia  Europe  North America  Oceania  South America
0       False   True   False          False    False          False
1       False   True   False          False    False          False
2       False   True   False          False    False          False
3       False   True   False          False    False          False
4        True  False   False          False    False          False
...       ...    ...     ...            ...      ...            ...
25475   False   True   False          False    False          False
25476   False   True   False          False    False          False
25477   False   True   False          False    False          False
25478   False   True   False          False    False          False
25479   False   True   False          False    False          False

[25480 rows x 6 columns]

In [26]:
visa_df  # datframe 
visa_df['continent']  # series 
visa_df['continent'].values  # array

array(['Asia', 'Asia', 'Asia', ..., 'Asia', 'Asia', 'Asia'], dtype=object)

In [27]:
visa_df = pd.read_csv(r"Visadataset.csv") 
pd.get_dummies(visa_df['continent'], dtype='int')

       Africa  Asia  Europe  North America  Oceania  South America
0           0     1       0              0        0              0
1           0     1       0              0        0              0
2           0     1       0              0        0              0
3           0     1       0              0        0              0
4           1     0       0              0        0              0
...       ...   ...     ...            ...      ...            ...
25475       0     1       0              0        0              0
25476       0     1       0              0        0              0
25477       0     1       0              0        0              0
25478       0     1       0              0        0              0
25479       0     1       0              0        0              0

[25480 rows x 6 columns]

## LableEncoder vs OneHotEncoder

- Generally we dont want a relation between input columns

- we need both aput columns are not correlated each other

- we need both input columns are **independent(X,Y)** each other

- we need both input columns are **perpendicular** each other

- we need both input columns are **Orthogonal** each other

- we need both input columns are **90 degrees phase shift** each other

- OneHotEncoder will achieve above

- But OneHotEncoder creates new columns

    - columns are incraese means dimensions are incresae

    - More dimension data need more processing time

    - More dimension data need more infra
 
    - this is called **curse of Demensionlity**