In [1]:
================== Data Analysis ====================
1.  Pandas               : Data frame analysis
2.  Numpy                : Numerical analysis
3.  Matplotlib           : Graphs and plots
4.  Seaborn              : Plots
5.  Bokeh                : Plots
6.  Plotly               : Plots

================== Machine Learning =================
7.  Stats                : Statistical models
8.  Scikit-learn         : ML models

================== Deep Learning ====================
9.  OpenCV               : Computer vision
10. Pillow               : Image operations
11. TensorFlow           : Neural network creation (Google)
12. Keras                : Neural networks
13. PyTorch              : Alternative to TensorFlow (Meta/Facebook)

====================== NLP ==========================
14. NLTK                 : Natural language toolkit
15. SpaCy                : Alternative to NLTK
16. WordCloud            : Most frequent words

==================== Scraping =======================
17. SQLite               : Database creation
18. Beautiful Soup       : Web scraping
19. Selenium             : Web automation

================== API Creation =====================
20. Flask                : Web framework
21. FastAPI              : Web framework
22. Gradio               : API/UI creation
23. Django               : Web framework

================== UI App Creation ==================
24. Streamlit            : UI/Apps for ML/DL

========== Transfer Learning Models (DL) ============
25. MobileNet            : CNN model
26. ResNet               : CNN model
27. VGGNet               : CNN model
28. Inception            : CNN model
29. YOLO                 : Object detection (Ultralytics)

========== Transfer Learning Models(DL) ===========
30. Word2Vec             : Word embeddings
31. GloVe                : Word embeddings

=============== Hugging Face Transformers ===========
32. BERT                 : Bi-directional Encoder Representations of transaformer

==================== Allen NLP ======================
33. AllenNLP             : NLP research library

====================== GenAI ========================
34. LangChain            : LLM orchestration
35. Google Gemini        : Google’s GenAI models
36. OpenAI GPT           : OpenAI’s LLMs
37. Amazon Bedrock       : AWS GenAI platform
38. Meta LLaMA           : Meta’s LLM family
==================== Image and Video Generations ====================
39. GAN models realted packages
40. SORA related packages
==================== Model deployment (MLOps) ====================
41. mlflow using databricks
42. kubeflow (GCP account)

==================== Cloud applications ====================
43. Azure ML realted packages
44. GCP VertexAI related packages
45. AWS Sagemaker realted packages

==================== small ====================
46. time
47. logging
48. math
49. random
50. env
51. os

SyntaxError: invalid character '’' (U+2019) (3740693155.py, line 58)

**Step-1: import packages**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
np.__version__

'2.1.3'

In [3]:
pd.__version__

'2.2.3'

In [5]:
sns.__version__

'0.13.2'

**Step-2:create a Dataframe using a list**

- data : ypur data is list & dict 

- index : we need to provide a list

- column : we need to provide a list

- dtype

In [4]:
names=['ramesh','suresh','satish']
pd.DataFrame(names,columns=['Names'])
# pd.dataframes(data,index,colunm)

    Names
0  ramesh
1  suresh
2  satish

**Step-3:change the index**

In [5]:
names=['ramesh','suresh','satish']
# idx=[]
pd.DataFrame(names,
             index=['A','B','C'],
             columns=['Names'])

    Names
A  ramesh
B  suresh
C  satish

**using variables**

In [6]:
names=['ramesh','suresh','satish']
idx=['A','b','C']
cols=['Names']
pd.DataFrame(names,
             index=idx,
             columns=cols)

    Names
A  ramesh
b  suresh
C  satish

**Step-4:Add multiple colunmns**

In [7]:
names=['ramesh','suresh','satish']
age=[20,22,24]
pd.DataFrame(zip(names,age),       # use the zip
            columns=['Names','Age'])

    Names  Age
0  ramesh   20
1  suresh   22
2  satish   24

**Step-5: Create the empty dataframes and update the columns**

In [8]:
df=pd.DataFrame()
df['names']=['ramesh','suresh','satish']
df['age']=[25,41,54]
df

    names  age
0  ramesh   25
1  suresh   41
2  satish   54

In [22]:
df=pd.DataFrame()
df['names']=['saurabh','gaikwad',4]
df['age']=[22,33,45]
df['sex']=['M','M','F']
df['address']=['nagar','hyd','usa']
df

     names  age sex address
0  saurabh   22   M   nagar
1  gaikwad   33   M     hyd
2        4   45   F     usa

**Step-6:Add a new column with existing dataframes**

In [23]:
names=['ramesh','suresh','satish']
age=[20,22,24]
city=['hyd','france','nagar']
df=pd.DataFrame(zip(names,age,city),    
            columns=['Names','Age','city'])
# df['City']=['hyd','france','nagar']
df
#####################################################

# names=['ramesh','suresh','satish']
# age=[20,22,24]
# df=pd.DataFrame(zip(names,age,city),    
#             columns=['Names','Age','city'])
# city=['hyd','france','nagar']
# df

    Names  Age    city
0  ramesh   20     hyd
1  suresh   22  france
2  satish   24   nagar

**Step-7:overwrite thr colunm values**

- I want to overwrite the my age values

- origrnally age is=[20,22,24]

- now i want to update the age = [34,35,36]

In [28]:
df['Age']=[34,35,36]
df

    Names  Age    city  age
0  ramesh   34     hyd   34
1  suresh   35  france   35
2  satish   36   nagar   36

In [13]:
df['Age']=[34,35,36]
df

    Names  Age    City  age
0  ramesh   34     hyd   34
1  suresh   35  france   35
2  satish   36   nagar   36

**Step-8:Drop the column**

- lables

- axis

- index

- coulmn

- inplace

In [14]:
# df.drop('age') # error
# df.drop('age',axis=0) # error
# df.drop('age',axis=1) #correct
# # here pyhton is assume the age s a label
# # python ask the Q : is it index lable or coloumn lable
# # axis=1 means for column
# # axis=0 menas for the rows
# # by default axix=0

In [15]:
# info.drop('age')   # error

In [16]:
# info.drop('age',axis=0)  # error

In [17]:
df.drop('age',axis=1)

    Names  Age    City
0  ramesh   34     hyd
1  suresh   35  france
2  satish   36   nagar

In [18]:
df

    Names  Age    City  age
0  ramesh   34     hyd   34
1  suresh   35  france   35
2  satish   36   nagar   36

In [19]:
df.drop(columns=['age'])

    Names  Age    City
0  ramesh   34     hyd
1  suresh   35  france
2  satish   36   nagar

In [20]:
df

    Names  Age    City  age
0  ramesh   34     hyd   34
1  suresh   35  france   35
2  satish   36   nagar   36

In [21]:
# no need if axis
df.drop(columns=['age'],inplace=True)

In [22]:
df

    Names  Age    City
0  ramesh   34     hyd
1  suresh   35  france
2  satish   36   nagar

In [23]:
# drop index =2
df.drop(2,
          axis=0)

    Names  Age    City
0  ramesh   34     hyd
1  suresh   35  france

In [24]:
df

    Names  Age    City
0  ramesh   34     hyd
1  suresh   35  france
2  satish   36   nagar

In [25]:
df.drop(index=2)

    Names  Age    City
0  ramesh   34     hyd
1  suresh   35  france

In [26]:
df.drop(index=1)    # drop the info using the index method

    Names  Age   City
0  ramesh   34    hyd
2  satish   36  nagar

**Step-9: rename the column**

In [27]:
names=['ramesh','suresh','satish']
age=[20,22,24]
df=pd.DataFrame(zip(names,age),    
            columns=['Names','Age'])
df['City']=['hyd','france','nagar']
df

    Names  Age    City
0  ramesh   20     hyd
1  suresh   22  france
2  satish   24   nagar

In [28]:
df
# i want  to change City column : city

    Names  Age    City
0  ramesh   20     hyd
1  suresh   22  france
2  satish   24   nagar

In [29]:
dict1={'City':'city'}
df.rename(dict1,axis=1)

    Names  Age    city
0  ramesh   20     hyd
1  suresh   22  france
2  satish   24   nagar

In [30]:
dict1={'City':'city'}
df.rename(columns=dict1,
           inplace=True)

In [31]:
df

    Names  Age    city
0  ramesh   20     hyd
1  suresh   22  france
2  satish   24   nagar

In [32]:
dict1={2:'B'}
df.rename(dict1,axis=0)

    Names  Age    city
0  ramesh   20     hyd
1  suresh   22  france
B  satish   24   nagar

In [33]:
dict1={'City':'city'}
df.rename(columns=dict1,
           inplace=True)

In [34]:
df1=pd.DataFrame()
df1['value']=[i for i in range(1,10)]
df1['square_value']=[i**2 for i in range(1,10)]
df1['cube_value']=[i**3 for i in range(1,10)]
df1

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16          64
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729

- len

- columns

- shape

- dtypes

- head

- tail

- df1.columns()
- df1.shape
- df1.dtypes
- df1.head
- df1.tail

In [35]:
df1.columns

Index(['value', 'square_value', 'cube_value'], dtype='object')

In [36]:
list(df1.columns)

['value', 'square_value', 'cube_value']

In [37]:
df1.shape

(9, 3)

In [38]:
df1.dtypes
# int will get integer
# float will get float
# string will get object

value           int64
square_value    int64
cube_value      int64
dtype: object

In [39]:
df1.head() # top 5 show   # df1.head(2)

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16          64
4      5            25         125

In [29]:
df1.tail()

NameError: name 'df1' is not defined

In [41]:
len(df1)

9

In [42]:
df1.isnull()
# we are asking a Q 
# a null value is avilable or not 
# True or False
# True means yes NULL avilable 
# False means yes NULL value not avilable

   value  square_value  cube_value
0  False         False       False
1  False         False       False
2  False         False       False
3  False         False       False
4  False         False       False
5  False         False       False
6  False         False       False
7  False         False       False
8  False         False       False

In [43]:
df1.isnull().sum()
# column wise NULL value count will disply

value           0
square_value    0
cube_value      0
dtype: int64

In [44]:
df1.info()   # information show

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   value         9 non-null      int64
 1   square_value  9 non-null      int64
 2   cube_value    9 non-null      int64
dtypes: int64(3)
memory usage: 348.0 bytes

**Step-10:**

- how to chnage a specipfic value fo a column 

- info.drop 

    - either it will drop column or index

- info.rename

    - either it will rename column or index

- info.replace

    -

In [45]:
df1

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16          64
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729

In [46]:
df1.replace(64,464)   # all the data will replace

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16         464
4      5            25         125
5      6            36         216
6      7            49         343
7      8           464         512
8      9            81         729

In [47]:
df1.replace({64:464,1:111})    # all the data will replace

   value  square_value  cube_value
0    111           111         111
1      2             4           8
2      3             9          27
3      4            16         464
4      5            25         125
5      6            36         216
6      7            49         343
7      8           464         512
8      9            81         729

**Step-11 : Selection of a column**

In [48]:
df1['cube_value']
# series 
# series looks like dataframe
# rows and columns

0      1
1      8
2     27
3     64
4    125
5    216
6    343
7    512
8    729
Name: cube_value, dtype: int64

In [49]:
type(df1)

pandas.core.frame.DataFrame

In [50]:
type(df1['cube_value'])

pandas.core.series.Series

In [51]:
df1.shape
# 2D

(9, 3)

In [52]:
df1['cube_value'].shape

(9,)

In [53]:
df1[['cube_value']]

   cube_value
0           1
1           8
2          27
3          64
4         125
5         216
6         343
7         512
8         729

In [54]:
type(df1[['cube_value']])
df1[['cube_value']].shape

(9, 1)

In [55]:
df1['cube_value'].replace(64,464,inplace=True)
# df1['square_value'].replace(64,464,inplace=True)

In [56]:
df1

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16         464
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729

**Step-12: How to append a row**

- loc

In [57]:
# info1.loc[rows,columns]
# info1.iloc[rows,columns]

# We can set particular row and columns using a list.[Start:stop:step]
df1.iloc[3:7,1:3]
df1.loc[3:7,['square_value','cube_value']]
cols=['square_value','cube_value']
df1.loc[3:7,cols]

   square_value  cube_value
3            16         464
4            25         125
5            36         216
6            49         343
7            64         512

In [58]:
df1.iloc[[2,3,4]]

   value  square_value  cube_value
2      3             9          27
3      4            16         464
4      5            25         125

In [59]:
df1.iloc[[2]]

   value  square_value  cube_value
2      3             9          27

In [60]:
df1.iloc[2]

value            3
square_value     9
cube_value      27
Name: 2, dtype: int64

In [61]:
df1.iloc[[2,3,4],[0,2]]
# 2,3,4 row
# 0 and 2 index

   value  cube_value
2      3          27
3      4         464
4      5         125

In [62]:
df1.iloc[2,0]

np.int64(3)

In [63]:
df1.iloc[:,0]

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
Name: value, dtype: int64

In [64]:
df1.iloc[2,:]

value            3
square_value     9
cube_value      27
Name: 2, dtype: int64

In [65]:
df1.iloc[[2],:]

   value  square_value  cube_value
2      3             9          27

In [66]:
df1.iloc[2:6,0]

2    3
3    4
4    5
5    6
Name: value, dtype: int64

In [67]:
df1.iloc[2,6:0]

Series([], Name: 2, dtype: int64)

In [68]:
df1

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16         464
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729

In [69]:
df1.loc[9]=[10,100,1000]
df1

   value  square_value  cube_value
0      1             1           1
1      2             4           8
2      3             9          27
3      4            16         464
4      5            25         125
5      6            36         216
6      7            49         343
7      8            64         512
8      9            81         729
9     10           100        1000

In [70]:
len(df1)

10

In [72]:
ID=len(df1)
df1.loc[ID]=[10,100,1000]
df1

    value  square_value  cube_value
0       1             1           1
1       2             4           8
2       3             9          27
3       4            16         464
4       5            25         125
5       6            36         216
6       7            49         343
7       8            64         512
8       9            81         729
9      10           100        1000
10     10           100        1000

## Step-13 save the dataframe

- we can save the dataframe 


- .csv

    
- .xlsx

    
- where i want to save : directory


- what is the file name to save : file name


- what is the type of file : extension 


- diffrent folder "C:\Users\Dell\Documents\NareshIT\Gen Ai\data_1.csv"


- diffrent folder "C:\Users\Dell\Documents\NareshIT\Gen Ai\data_1.xlsx"


- same folder : directlly file name "data_1.csv" or "data_1.xlsx"

In [73]:
csv_path=r"C:\Users\Dell\Documents\NareshIT\Gen Ai\data_1.csv"
excel_path=r"C:\Users\Dell\Documents\NareshIT\Gen Ai\data_1.xlsx"
df1.to_csv(csv_path)
df1.to_excel(excel_path)

In [74]:
csv_path=r"data_1.csv"
excel_path=r"data_1.xlsx"
df1.to_csv(csv_path)
df1.to_excel(excel_path)

## Step-14 : How to read the data

In [75]:
csv_path=r"data_1.csv"
pd.read_csv(csv_path)

    Unnamed: 0  value  square_value  cube_value
0            0      1             1           1
1            1      2             4           8
2            2      3             9          27
3            3      4            16         464
4            4      5            25         125
5            5      6            36         216
6            6      7            49         343
7            7      8            64         512
8            8      9            81         729
9            9     10           100        1000
10          10     10           100        1000

In [76]:
csv_path=r"data_1.csv"
excel_path=r"data_1.xlsx"
df1.to_csv(csv_path,index=False)
df1.to_excel(excel_path,index=False)

In [77]:
csv_path=r"data_1.csv"
pd.read_csv(csv_path)

    value  square_value  cube_value
0       1             1           1
1       2             4           8
2       3             9          27
3       4            16         464
4       5            25         125
5       6            36         216
6       7            49         343
7       8            64         512
8       9            81         729
9      10           100        1000
10     10           100        1000

In [78]:
excel_path=r"data_1.xlsx"              # path
df1.to_excel(excel_path,index=False)   # save the data 
pd.read_excel(excel_path)              # read the data

    value  square_value  cube_value
0       1             1           1
1       2             4           8
2       3             9          27
3       4            16         464
4       5            25         125
5       6            36         216
6       7            49         343
7       8            64         512
8       9            81         729
9      10           100        1000
10     10           100        1000

In [18]:
csv_path=r"C:\Users\Dell\Documents\NareshIT\python_sessions\datafiles\bank.csv"
pd.read_csv(csv_path)

     age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"
0     30;"unemployed";"married";"primary";"no";1787;...
1     33;"services";"married";"secondary";"no";4789;...
2     35;"management";"single";"tertiary";"no";1350;...
3     30;"management";"married";"tertiary";"no";1476...
4     59;"blue-collar";"married";"secondary";"no";0;...
...                                                 ...
4516  33;"services";"married";"secondary";"no";-333;...
4517  57;"self-employed";"married";"tertiary";"yes";...
4518  57;"technician";"married";"secondary";"no";295...
4519  28;"blue-collar";"married";"secondary";"no";11...
4520  44;"entrepreneur";"single";"tertiary";"no";113...

[4521 rows x 1 columns]

In [17]:
csv_path=r"C:\Users\Dell\Documents\NareshIT\python_sessions\datafiles\bank.csv"
pd.read_csv(csv_path)

     age;"job";"marital";"education";"default";"balance";"housing";"loan";"contact";"day";"month";"duration";"campaign";"pdays";"previous";"poutcome";"y"
0     30;"unemployed";"married";"primary";"no";1787;...
1     33;"services";"married";"secondary";"no";4789;...
2     35;"management";"single";"tertiary";"no";1350;...
3     30;"management";"married";"tertiary";"no";1476...
4     59;"blue-collar";"married";"secondary";"no";0;...
...                                                 ...
4516  33;"services";"married";"secondary";"no";-333;...
4517  57;"self-employed";"married";"tertiary";"yes";...
4518  57;"technician";"married";"secondary";"no";295...
4519  28;"blue-collar";"married";"secondary";"no";11...
4520  44;"entrepreneur";"single";"tertiary";"no";113...

[4521 rows x 1 columns]

In [19]:
csv_path=r"bank.csv"
pd.read_csv(csv_path)

FileNotFoundError: [Errno 2] No such file or directory: 'bank.csv'